#!/usr/bin/env node
/**
 * Audio Generation Script — ElevenLabs TTS
 * Usage: ELEVENLABS_API_KEY=your_key node scripts/generate_audio.js
 *
 * Generates .mp3 files for all major narration phrases and
 * writes the resulting audioMap to src/utils/audioMap.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { pathToFileURL } from 'url';
import { worlds } from '../src/data/questionBank.js';
import { storyPanels } from '../src/data/storyContent.js';
import {
  introNarration,
  wonderNarration,
  storyNarration,
  simulateNarration,
  feedbackNarration,
  reflectNarration,
} from '../src/utils/narration.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, '..');
const AUDIO_DIR = path.join(ROOT, 'public', 'assets', 'audio');
const MAP_FILE  = path.join(ROOT, 'src', 'utils', 'audioMap.js');

const API_KEY  = process.env.ELEVENLABS_API_KEY ?? process.env.VITE_ELEVENLABS_API_KEY;
const VOICE_ID = 'Xb7hH8MSUJpSbSDYk0k2'; // Alice
const MODEL    = 'eleven_multilingual_v2';

if (!API_KEY) {
  console.error('❌  ELEVENLABS_API_KEY not set. Export ELEVENLABS_API_KEY or VITE_ELEVENLABS_API_KEY first.');
  process.exit(1);
}

function collectTextEntries() {
  const entries = [];

  entries.push(...introNarration());
  entries.push(...wonderNarration());
  for (let i = 0; i < 4; i++) entries.push(...storyNarration(i));
  for (let i = 0; i < 3; i++) entries.push(...simulateNarration(i));
  entries.push(...feedbackNarration(true));
  entries.push(...feedbackNarration(false));
  entries.push(...reflectNarration());

  for (const world of worlds) {
    for (const question of world.questions) {
      entries.push({ text: question.text, style: 'question' });
    }
  }

  // Include full story panel texts and mascot speeches so story narration is complete
  for (const p of storyPanels) {
    if (p.text) entries.push({ text: p.text, style: 'statement' });
    if (p.mascotSpeech) entries.push({ text: p.mascotSpeech, style: 'statement' });
  }

  const seen = new Set();
  return entries.filter(entry => {
    if (seen.has(entry.text)) return false;
    seen.add(entry.text);
    return true;
  });
}

// ── Phrases to pre-generate ──────────────────────────────────────
const phrases = collectTextEntries();

// ── Voice style presets ──────────────────────────────────────────
const STYLE_SETTINGS = {
  statement:    { stability: 0.55, similarity_boost: 0.75, style: 0.20 },
  instruction:  { stability: 0.60, similarity_boost: 0.75, style: 0.15 },
  question:     { stability: 0.45, similarity_boost: 0.80, style: 0.35 },
  encouragement:{ stability: 0.40, similarity_boost: 0.80, style: 0.45 },
  emphasis:     { stability: 0.65, similarity_boost: 0.80, style: 0.10 },
  thinking:     { stability: 0.50, similarity_boost: 0.70, style: 0.30 },
  celebration:  { stability: 0.35, similarity_boost: 0.85, style: 0.60 },
};

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '_').slice(0, 50);
}

async function generate(text, style, index) {
  const settings = STYLE_SETTINGS[style] ?? STYLE_SETTINGS.statement;
  const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${VOICE_ID}`, {
    method: 'POST',
    headers: { 'xi-api-key': API_KEY, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      text,
      model_id: MODEL,
      voice_settings: settings,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`ElevenLabs API error ${res.status}: ${err}`);
  }

  const buffer = Buffer.from(await res.arrayBuffer());
  const filename = `audio_${slugify(text)}_${index}.mp3`;
  const filepath  = path.join(AUDIO_DIR, filename);
  fs.writeFileSync(filepath, buffer);
  return `/assets/audio/${filename}`;
}

async function main() {
  if (!fs.existsSync(AUDIO_DIR)) fs.mkdirSync(AUDIO_DIR, { recursive: true });

  let existingMap = {};
  try {
    const mod = await import(pathToFileURL(MAP_FILE).href);
    existingMap = mod.audioMap ?? {};
  } catch {
    existingMap = {};
  }

  const map = { ...existingMap };
  let ok = 0, fail = 0;

  for (let i = 0; i < phrases.length; i++) {
    const { text, style } = phrases[i];
    if (map[text] && fs.existsSync(path.join(ROOT, 'public', map[text]))) {
      continue;
    }
    process.stdout.write(`[${i + 1}/${phrases.length}] "${text.slice(0, 40)}…" `);
    try {
      const url = await generate(text, style, i);
      map[text] = url;
      ok++;
      console.log('✅');
      // Rate-limit: 3 req/s
      await new Promise(r => setTimeout(r, 340));
    } catch (err) {
      fail++;
      console.log(`❌  ${err.message}`);
    }
  }

  // Write audioMap.js
  const mapSrc = `// Auto-generated by scripts/generate_audio.js — DO NOT EDIT\nexport const audioMap = ${JSON.stringify(map, null, 2)};\n`;
  fs.writeFileSync(MAP_FILE, mapSrc, 'utf8');

  console.log(`\n✅  ${ok} files generated, ${fail} failed.`);
  console.log(`📝  audioMap written to src/utils/audioMap.js`);
}

main().catch(e => { console.error(e); process.exit(1); });
